# Sample Logstash configuration for creating a simple
# Beats -> Logstash -> Elasticsearch pipeline.

input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    split => { "message" => "|" }

    add_field => {
      "userId" => "%{[message][1]}"
      "visit" => "%{[message][2]}"
      "date" => "%{[message][3]}"
    }

    convert => {
      "userId" => "integer"
      "visit" => "string"
      "date" => "string"
    }
  }
}


output {
  # # 输出到控制台（开发测试用）
  # stdout { codec => rubydebug }

  # 输出到 Elasticsearch
  elasticsearch {
    hosts => ["http://localhost:9200"]
    #index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
    #user => "elastic"
    #password => "changeme"
  }
}

